language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
    - language: generic
      python: 3.3
      os: osx
    - language: generic
      python: 3.4
      os: osx
    - language: generic
      python: 3.5
      os: osx
    - language: generic
      python: 3.6
      os: osx

before_install:
  - pip install --quiet codecov wheel

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
